name: Wayfinder deploy workflow

on:
  workflow_call:
    inputs:
      registry:
        description: 'Container registry domain'
        required: true
        type: string
      image-name:
        description: 'Name of the Docker image to build'
        required: true
        type: string
      image-tag:
        description: 'Image tag to deploy'
        required: true
        default: 'latest'
        type: string
      wayfinder-server:
        description: 'Wayfinder server URL'
        required: true
        type: string
      wayfinder-workspace:
        description: 'Wayfinder workspace name'
        required: true
        type: string
      wayfinder-resource-owner:
        description: 'Wayfinder resource owner'
        required: true
        type: string
      application-name:
        description: 'Application name'
        required: true
        type: string
      application-stage:
        description: 'Application stage'
        required: true
        type: string
    secrets:
      wayfinder-token:
        description: 'Wayfinder token'
        required: true
        
defaults:
  run:
    shell: bash

env:
  WAYFINDER_SERVER: ${{ inputs.wayfinder-server }}
  WAYFINDER_TOKEN: ${{ secrets.wayfinder-token }}
  WAYFINDER_WORKSPACE: ${{ inputs.wayfinder-workspace }}
  WAYFINDER_RESOURCE_OWNER: ${{ inputs.wayfinder-resource-owner }}

jobs:
  wf:
    name: "Wayfinder toolbox"
    runs-on: ubuntu-latest
    container: quay.io/appvia-wf-dev/wftoolbox:latest
    outputs:
      version: ${{ steps.wayfinder.outputs.version }}
      toolbox: ${{ steps.wayfinder.outputs.toolbox }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Wayfinder toolbox version
        id: wayfinder
        uses: appvia-demos/ci-reusable-workflows/.github/actions/wayfinder-toolbox-version@main

  wf-diff:
    name: "Wayfinder Diff"
    runs-on: ubuntu-latest
    needs:
      - wf
    container: ${{ needs.wf.outputs.toolbox }}
    outputs:
      result: ${{ steps.diff.outputs.result }}
      stdout: ${{ steps.diff.outputs.stdout }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Wayfinder diff
        id: diff
        uses: appvia-demos/ci-reusable-workflows/.github/actions/wayfinder-diff@main

  wf-apply:
    name: "Wayfinder Apply"
    needs:
      - wf
      - wf-diff
    runs-on: ubuntu-latest
    container: ${{ needs.wf.outputs.toolbox }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Wayfinder apply
        id: apply
        uses: appvia-demos/ci-reusable-workflows/.github/actions/wayfinder-apply@main
        env:
          APP_NAME: ${{ inputs.application-name }}
          APP_IMAGE: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          APP_STAGE: ${{ inputs.application-stage }}
